# Generated by Django 6.0.3 on 2026-03-25 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Similarity score between 0 and 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports', to='assignments.assignment')),
                ('submission1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports_as_first', to='submissions.submission')),
                ('submission2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports_as_second', to='submissions.submission')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'unique_together': {('submission1', 'submission2')},
            },
        ),
    ]
