# Generated by Django 6.0.3 on 2026-03-24 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., HSE211', max_length=20, unique=True)),
                ('title', models.CharField(help_text='e.g., Introduction to Programming', max_length=200)),
                ('faculty', models.CharField(blank=True, help_text='e.g., Faculty of Computing', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('grading_config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.course')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('stdout', 'Stdout (run script, compare output)'), ('function', 'Function (call function, compare return)')], default='stdout', max_length=10)),
                ('input_data', models.TextField(blank=True, help_text='Input for stdin (only for stdout mode)')),
                ('expected_output', models.TextField(blank=True, help_text='Expected output (stdout mode) or return value (function mode)')),
                ('is_hidden', models.BooleanField(default=False)),
                ('function_name', models.CharField(blank=True, help_text='Name of function to call', max_length=100)),
                ('arguments', models.JSONField(blank=True, default=list, help_text='List of arguments to pass')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assignments.assignment')),
            ],
        ),
    ]
