# Generated by Django 6.0.3 on 2026-03-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='required_function_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='required_param_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
