# Generated by Django 6.0.3 on 2026-03-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_required_function_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grading_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
