# Generated by Django 6.0.3 on 2026-03-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_grading_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='arguments',
            field=models.JSONField(blank=True, default=list, help_text='List of arguments to pass'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='function_name',
            field=models.CharField(blank=True, help_text='Name of function to call', max_length=100),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(choices=[('stdout', 'Stdout (run script, compare output)'), ('function', 'Function (call function, compare return)')], default='stdout', max_length=10),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Expected output (stdout mode) or return value (function mode)'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, help_text='Input for stdin (only for stdout mode)'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
